import type { AuditSection } from "@/types/audit";

export const AUDIT_SECTIONS: AuditSection[] = [
  {
    id: "lead-capture",
    number: 1,
    title: "Lead Capture",
    goal: "Make sure every potential customer is captured properly.",
    questions: [
      { id: "lc_1", text: "Do you know where your leads come from?" },
      { id: "lc_2", text: "Are leads from WhatsApp, Instagram, email, website, referrals, events, and ads recorded in one place?" },
      { id: "lc_3", text: "Do you have a clear intake form or qualification process for new enquiries?" },
      { id: "lc_4", text: "Are leads tagged by source, urgency, deal size, and customer type?" },
      { id: "lc_5", text: "Can you easily see how many new leads you received this week or month?" },
    ],
    aiOpportunities: [
      "Auto-create CRM entries from forms, emails, or WhatsApp inquiries",
      "Use AI to classify and score lead quality on arrival",
      "Summarize inbound messages into structured CRM fields",
      "Auto-tag leads by source, service need, budget, or urgency",
    ],
    recommendation: {
      problem: "Leads are entering through multiple channels but not being centralized or tracked systematically.",
      whyItMatters: "Without centralized lead capture you cannot measure demand, follow up reliably, or understand which channels are working. Revenue is leaking at the very first touchpoint.",
      firstFix: "Choose one CRM or tracker — even a shared spreadsheet — and set a rule that every new lead, regardless of source, gets added within 24 hours.",
      aiOpportunity: "AI can auto-create CRM entries from inbound forms, emails, and messages. It can classify lead quality, auto-tag by source and urgency, and summarize unstructured conversations into structured fields.",
      thirtyDayAction: "Week 1: Choose a CRM (HubSpot Free, Notion, or Airtable). Week 2: Build a simple lead intake form for your main channels. Week 3: Backfill active leads. Week 4: Set up tagging logic and test auto-entry from at least one channel.",
    },
  },
  {
    id: "sales-pipeline",
    number: 2,
    title: "Sales Pipeline",
    goal: "Stop relying on memory to manage active opportunities.",
    questions: [
      { id: "sp_1", text: "Do you have a CRM or pipeline board where all opportunities live?" },
      { id: "sp_2", text: "Are all active opportunities tracked by pipeline stage?" },
      { id: "sp_3", text: "Do you know which leads are new, contacted, qualified, quoted, negotiating, won, or lost?" },
      { id: "sp_4", text: "Is there a clear documented next step for every active lead?" },
      { id: "sp_5", text: "Can you see the total potential revenue value sitting in your pipeline right now?" },
    ],
    aiOpportunities: [
      "Auto-update lead stage based on email or form activity",
      "Generate next-step reminders for stale leads automatically",
      "Summarize sales calls and extract deal notes",
      "Flag leads that have not been followed up within your target window",
    ],
    recommendation: {
      problem: "Opportunities are being tracked from memory or in scattered chats without a clear view of the pipeline.",
      whyItMatters: "A founder managing deals from memory will always drop leads, delay follow-ups, and misread their pipeline. You cannot manage what you cannot see.",
      firstFix: "Define 5–7 clear pipeline stages and move every active opportunity into the right stage today. Assign a next action and a date to each one.",
      aiOpportunity: "AI can auto-update deal stages based on email activity, generate summaries for stale leads, extract key points from sales calls, and flag deals that need immediate attention.",
      thirtyDayAction: "Week 1: Define pipeline stages and enter all active deals. Week 2: Add next-action dates to every deal. Week 3: Set up a weekly pipeline review habit. Week 4: Add value estimates and identify your top 5 deals to close this month.",
    },
  },
  {
    id: "follow-up",
    number: 3,
    title: "Follow-Up System",
    goal: "Make sure sales are not lost because the founder forgot to follow up.",
    questions: [
      { id: "fu_1", text: "Do you have a standard follow-up cadence for new leads and active deals?" },
      { id: "fu_2", text: "Are follow-up reminders automatic rather than relying on memory?" },
      { id: "fu_3", text: "Do you have visibility into which leads have gone cold or are overdue?" },
      { id: "fu_4", text: "Do you have message templates for different lead types and pipeline stages?" },
      { id: "fu_5", text: "Do you track why leads do not convert so you can improve over time?" },
    ],
    aiOpportunities: [
      "Draft personalized follow-up messages based on lead context",
      "Detect unanswered leads and surface them for immediate action",
      "Summarize previous conversations and suggest next-best action",
      "Generate re-engagement campaigns for leads that went cold months ago",
    ],
    recommendation: {
      problem: "Follow-up depends on founder memory, which means leads are slipping through without a second touch.",
      whyItMatters: "Most deals require 3–7 touchpoints before converting. Businesses that follow up systematically close more deals from the same lead volume — without spending more on acquisition.",
      firstFix: "Write a simple 5-step follow-up sequence: Day 0 (initial response), Day 2 (question or value add), Day 5 (follow-up), Day 10 (soft nudge), Day 21 (final check-in). Create one template for each step.",
      aiOpportunity: "AI can draft personalized follow-up messages, detect unanswered leads, summarize previous conversations, suggest next-best actions, and generate re-engagement sequences for cold leads.",
      thirtyDayAction: "Week 1: Write 5 follow-up email/message templates. Week 2: Set up reminders in your CRM. Week 3: Review all cold leads from the past 3 months and send re-engagement messages. Week 4: Set up at least one automated follow-up trigger.",
    },
  },
  {
    id: "offer-pricing-proposal",
    number: 4,
    title: "Offer, Pricing & Proposal Workflow",
    goal: "Make the business easier to buy from.",
    questions: [
      { id: "opp_1", text: "Is your core offer clear enough to explain in one sentence?" },
      { id: "opp_2", text: "Do customers clearly understand what they get, how it works, and what it costs?" },
      { id: "opp_3", text: "Do you have standard packages or a defined pricing logic?" },
      { id: "opp_4", text: "Do you have reusable proposal or quote templates?" },
      { id: "opp_5", text: "Do you track which offers or packages convert best?" },
    ],
    aiOpportunities: [
      "Generate first-draft proposals from discovery call notes",
      "Turn transcripts into structured proposal outlines in minutes",
      "Create pricing comparison tables and package summaries",
      "Build and maintain reusable sales scripts and objection responses",
    ],
    recommendation: {
      problem: "The offer is unclear, proposals take too long to create, or pricing is inconsistent — making it harder for prospects to say yes.",
      whyItMatters: "A confusing or slow proposal process directly costs revenue. Prospects who do not understand what they are buying, or who wait too long for a quote, will move on or compare you unfavorably.",
      firstFix: "Write one clear sentence that explains: who you help, what you do, and what changes for them. Then build one reusable proposal template you can customize in 30 minutes or less.",
      aiOpportunity: "AI can turn discovery call notes into proposal first-drafts, generate pricing tables, rewrite offer descriptions for clarity, and build a library of reusable sales responses.",
      thirtyDayAction: "Week 1: Write a one-sentence offer statement and test it on 5 prospects. Week 2: Build one proposal template with standard sections. Week 3: Define 2–3 pricing packages with clear deliverables. Week 4: Build an objection-response document.",
    },
  },
  {
    id: "customer-journey",
    number: 5,
    title: "Customer Journey",
    goal: "Understand how someone moves from stranger to paying customer.",
    questions: [
      { id: "cj_1", text: "Do you know the full path a customer takes from first awareness to purchase?" },
      { id: "cj_2", text: "Are the main drop-off or friction points in that journey visible to you?" },
      { id: "cj_3", text: "Do you know what customers need to see, hear, or believe before they are ready to buy?" },
      { id: "cj_4", text: "Do you systematically collect and review customer objections?" },
      { id: "cj_5", text: "Do you have content, case studies, or materials that answer common pre-purchase questions?" },
    ],
    aiOpportunities: [
      "Analyze customer FAQs and objections to identify trust gaps",
      "Generate educational content addressing common purchase blockers",
      "Draft onboarding email sequences for new customers",
      "Summarize customer conversations to surface recurring friction",
    ],
    recommendation: {
      problem: "The path from first contact to closed deal has not been mapped, and the friction points where prospects drop off are unknown.",
      whyItMatters: "If you do not know where customers lose interest or trust, you cannot fix the drop-off. Small improvements at key journey stages compound into large revenue gains.",
      firstFix: "Draw a simple map: Awareness → Interest → Trust → Decision → Onboarding. For each stage, write: what does the prospect need, what is the biggest friction, and what do you currently provide?",
      aiOpportunity: "AI can analyze customer objections, identify trust gaps, generate case study drafts, create educational content for each journey stage, and draft onboarding sequences.",
      thirtyDayAction: "Week 1: Map your customer journey in a simple document. Week 2: Identify the 3 most common objections. Week 3: Create one piece of content addressing each. Week 4: Add these assets to your sales and follow-up process.",
    },
  },
  {
    id: "bd-partnerships",
    number: 6,
    title: "Business Development & Partnerships",
    goal: "Create repeatable ways to generate opportunities beyond random inbound.",
    questions: [
      { id: "bd_1", text: "Do you have a clear picture of your highest-value customer segments and where to find them?" },
      { id: "bd_2", text: "Do you have a defined target list of potential partners or strategic relationships?" },
      { id: "bd_3", text: "Do you have an outreach message that is specific, relevant, and tested?" },
      { id: "bd_4", text: "Are business development conversations tracked in a CRM or pipeline?" },
      { id: "bd_5", text: "Do you have a clear partnership offer or referral structure that others can easily promote?" },
    ],
    aiOpportunities: [
      "Research and build targeted prospect and partner lists at scale",
      "Draft personalized outreach messages from prospect context",
      "Summarize BD calls and extract key relationship notes",
      "Generate partnership proposal and referral program documentation",
    ],
    recommendation: {
      problem: "Business development is reactive — dependent on inbound and personal network — without a repeatable outreach and partnership system.",
      whyItMatters: "Relying only on inbound makes revenue unpredictable. A structured BD process — even a simple one — creates compounding pipeline momentum that does not depend on algorithm or ad spend.",
      firstFix: "Identify 3 partner categories where your target customer already exists. Write one specific, short outreach message for each category. Reach out to 5 prospects per category this month.",
      aiOpportunity: "AI can research and build prospect lists, draft personalized outreach, summarize BD conversations, track relationship context, and generate partnership proposal templates.",
      thirtyDayAction: "Week 1: Define 3 partner archetypes with clear customer overlap. Week 2: Build a list of 20 targets per category. Week 3: Write and test one outreach message per category. Week 4: Send first batch and track responses in your CRM.",
    },
  },
  {
    id: "operations-sops",
    number: 7,
    title: "Operations & SOPs",
    goal: "Reduce founder dependency by documenting how the business actually runs.",
    questions: [
      { id: "op_1", text: "Are your most repeated tasks documented in a way someone else could follow?" },
      { id: "op_2", text: "Can a team member complete key workflows without asking you every step?" },
      { id: "op_3", text: "Do you have clear SOPs for sales, onboarding, delivery, customer support, and reporting?" },
      { id: "op_4", text: "Are tasks assigned with clear owners, deadlines, and visibility?" },
      { id: "op_5", text: "Do you have a consistent weekly operating rhythm — a recurring structure for reviews and priorities?" },
    ],
    aiOpportunities: [
      "Turn messy notes and voice memos into structured SOPs",
      "Generate checklists and templates from recurring task patterns",
      "Summarize meetings into structured action items automatically",
      "Build internal knowledge bases from founder knowledge and conversations",
    ],
    recommendation: {
      problem: "Key workflows exist in the founder's head — not written down — creating a bottleneck, blocking delegation, and making quality inconsistent.",
      whyItMatters: "Founder-dependent operations limit how fast you can grow. You cannot hire effectively, delegate confidently, or maintain quality at scale without documented processes.",
      firstFix: "Pick the one task you do most often and document it step by step — even in a simple Google Doc. Add screenshots where relevant. Do this for one new task per week.",
      aiOpportunity: "AI can turn rough notes, recordings, or scattered instructions into formatted SOPs. It can also generate task checklists, summarize weekly meetings into actions, and build internal FAQs from founder knowledge.",
      thirtyDayAction: "Week 1: List your 10 most repeated tasks. Week 2: Document the top 3 in simple step-by-step format. Week 3: Add onboarding and delivery SOPs. Week 4: Set up a weekly operating rhythm and test delegating one task.",
    },
  },
  {
    id: "reporting-metrics",
    number: 8,
    title: "Reporting & Metrics",
    goal: "Know what is actually working — without spending hours on manual reports.",
    questions: [
      { id: "rm_1", text: "Do you have a weekly dashboard or report that gives you a clear business snapshot?" },
      { id: "rm_2", text: "Do you know how many leads came in this week and which channels they came from?" },
      { id: "rm_3", text: "Do you know your conversion rate from lead to paying customer?" },
      { id: "rm_4", text: "Do you know your average deal size, customer lifetime value, or revenue per engagement?" },
      { id: "rm_5", text: "Do you know which channels, partners, or activities drive your best customers?" },
    ],
    aiOpportunities: [
      "Generate weekly business summaries from CRM and pipeline data",
      "Flag bottlenecks and pipeline gaps without manual analysis",
      "Analyze lost deal patterns and surface trends automatically",
      "Turn raw CRM data into structured founder-friendly reports",
    ],
    recommendation: {
      problem: "Business performance is not measured consistently, so decisions are made by gut feel rather than data.",
      whyItMatters: "You cannot improve what you do not measure. Founders who track even 5 core metrics weekly make better decisions, catch problems earlier, and have far stronger conversations with investors or partners.",
      firstFix: "Track 5 numbers every week: new leads, proposals sent, deals won, revenue closed, and pipeline value. Even a simple spreadsheet updated every Monday is better than no visibility.",
      aiOpportunity: "AI can generate weekly business summaries from CRM data, flag overdue follow-ups, identify patterns in lost deals, and turn raw pipeline data into clear reports.",
      thirtyDayAction: "Week 1: Define your 5–10 core metrics. Week 2: Build a simple tracking sheet or dashboard. Week 3: Set up a 15-minute weekly review habit. Week 4: Add lost-deal tracking and identify your best lead source.",
    },
  },
  {
    id: "support-retention",
    number: 9,
    title: "Customer Support & Retention",
    goal: "Keep customers happy and coming back without overwhelming the founder.",
    questions: [
      { id: "sr_1", text: "Do you have a system for tracking customer issues, requests, and feedback?" },
      { id: "sr_2", text: "Do you know the most common questions or problems customers have after buying?" },
      { id: "sr_3", text: "Do you have templates for common customer replies and support situations?" },
      { id: "sr_4", text: "Do you have a structured onboarding flow that helps new customers get value quickly?" },
      { id: "sr_5", text: "Do you have a process for requesting referrals, testimonials, reviews, or repeat business?" },
    ],
    aiOpportunities: [
      "Draft customer replies and support responses from context",
      "Build a living FAQ document from historical support conversations",
      "Create customer onboarding email and message sequences",
      "Identify repeat complaints and surface them as improvement signals",
    ],
    recommendation: {
      problem: "Customer support is handled ad hoc, without templates, tracking, or a proactive retention and referral process.",
      whyItMatters: "Customer support quality directly affects retention, reviews, and referrals — three of the highest-ROI growth levers for a founder-led business. A poor support experience also takes disproportionate time without a system.",
      firstFix: "Write answers to your 10 most common customer questions. Turn them into a shared FAQ. Add a structured onboarding sequence that delivers early value and builds trust before the first problem arises.",
      aiOpportunity: "AI can draft personalized support replies, build FAQ documents from conversation history, create onboarding email sequences, and identify recurring complaints that signal product or service gaps.",
      thirtyDayAction: "Week 1: Document your 10 most common customer questions. Week 2: Build a simple onboarding checklist or email sequence. Week 3: Create reply templates for the top 5 support situations. Week 4: Set up a referral or review request as part of your standard delivery close.",
    },
  },
  {
    id: "ai-readiness",
    number: 10,
    title: "AI Readiness",
    goal: "Make sure AI is used practically and safely — not randomly.",
    questions: [
      { id: "ai_1", text: "Have you identified your most repetitive manual workflows where AI could save the most time?" },
      { id: "ai_2", text: "Do you know which tasks are safe to automate fully versus which need human review?" },
      { id: "ai_3", text: "Is your business data organized and clean enough for AI tools to use effectively?" },
      { id: "ai_4", text: "Do you have clear rules for handling customer data, private information, and quality control in AI workflows?" },
      { id: "ai_5", text: "Are AI tools connected to your actual workflows, or used in isolation and manually?" },
    ],
    aiOpportunities: [
      "Map workflows before picking tools — identify where AI adds the most leverage",
      "Start AI adoption with drafting, summarizing, classifying, and researching tasks",
      "Build AI agents to monitor pipeline activity and surface exceptions",
      "Create a simple AI usage policy to protect customer data and maintain quality",
    ],
    recommendation: {
      problem: "AI tools are being used randomly or experimentally without a clear framework for where they fit in the business.",
      whyItMatters: "AI used without a system often creates more noise than value — adding tools without fixing the underlying process. The real leverage comes from connecting AI to specific, repeatable workflows.",
      firstFix: "List your 10 most repetitive tasks. Mark each as: (a) safe to automate, (b) needs human review, or (c) too sensitive. Start with category (a) only and build from there.",
      aiOpportunity: "AI is most valuable in drafting, summarizing, classifying, and researching. Start there. Then build connected workflows where AI handles the first version and the founder handles the final decision.",
      thirtyDayAction: "Week 1: Audit your top 10 repetitive tasks and categorize them. Week 2: Pick one safe-to-automate task and build a simple AI workflow. Week 3: Test and refine it. Week 4: Document the workflow and identify the next candidate.",
    },
  },
  {
    id: "founder-time",
    number: 11,
    title: "Founder Time Leverage",
    goal: "Free the founder from low-value work so they can focus on what actually drives growth.",
    questions: [
      { id: "ft_1", text: "Do you know where your time actually goes each week — broken down by category?" },
      { id: "ft_2", text: "Are you still personally doing work that could be delegated, templated, or automated?" },
      { id: "ft_3", text: "Do you spend enough time on revenue-generating activities — sales, partnerships, product, or strategy?" },
      { id: "ft_4", text: "Are you regularly answering the same internal questions or repeating the same explanations?" },
      { id: "ft_5", text: "Do you have a clear framework for deciding what to stop, delegate, or automate before taking on new work?" },
    ],
    aiOpportunities: [
      "Meeting summaries, email drafts, and research tasks handled by AI",
      "Generate task lists and priority frameworks from weekly reviews",
      "Build internal knowledge bases so the same questions stop reaching the founder",
      "Use AI to produce first drafts of proposals, reports, and communications",
    ],
    recommendation: {
      problem: "The founder is deep in low-leverage work — admin, repeating explanations, or manual tasks that drain time from revenue-generating activities.",
      whyItMatters: "Founder time is the scarcest resource in an early-stage business. Every hour spent on low-value work is an hour not spent on sales, partnerships, hiring, or product. This is where most growth stalls.",
      firstFix: "Track your time for one week across these categories: revenue work, delivery, admin, team, product, and firefighting. Then identify the single biggest time drain and build a plan to reduce it by 50% in 30 days.",
      aiOpportunity: "AI can handle first drafts, meeting summaries, research tasks, and internal documentation — returning 5–10 hours per week to founders who use it consistently.",
      thirtyDayAction: "Week 1: Track time for 5 working days by category. Week 2: Identify your top 3 time drains. Week 3: Build templates or AI workflows for each. Week 4: Delegate or automate at least one task that currently takes more than 2 hours per week.",
    },
  },
  {
    id: "investor-readiness",
    number: 12,
    title: "Investor & Strategic Readiness",
    goal: "Make sure the business can be explained and evaluated clearly by investors, partners, or strategic buyers.",
    questions: [
      { id: "ir_1", text: "Can you explain your business clearly in one sentence — market, customer, and value?" },
      { id: "ir_2", text: "Do you have clean, current traction metrics that tell the story of business momentum?" },
      { id: "ir_3", text: "Do you have a basic financial model or revenue forecast — even a simple one?" },
      { id: "ir_4", text: "Do you have an organized data room or business folder with key documents ready?" },
      { id: "ir_5", text: "Do you know your key risks and have clear answers to the most likely investor or partner questions?" },
    ],
    aiOpportunities: [
      "Draft investor FAQ and objection response documents",
      "Turn operating data into a clear, structured business narrative",
      "Build data room checklists and organize materials systematically",
      "Summarize traction metrics into compelling pitch-ready language",
    ],
    recommendation: {
      problem: "The business cannot yet be presented clearly or evaluated easily by an external party — whether an investor, strategic partner, or potential acquirer.",
      whyItMatters: "Even if you are not raising capital, the discipline of investor readiness — clean metrics, clear narrative, organized materials — makes you a better operator and a more credible partner.",
      firstFix: "Write a one-paragraph business summary: what the business does, who it serves, what traction it has, and what the growth opportunity is. Share it with 3 advisors and ask what questions it leaves unanswered.",
      aiOpportunity: "AI can help clean up your business narrative, draft investor FAQs, prepare objection responses, organize a data room checklist, and turn operating data into clear investor-friendly language.",
      thirtyDayAction: "Week 1: Write and test a one-paragraph business summary. Week 2: Compile traction metrics into a clean one-page summary. Week 3: Build a simple financial model with revenue history and 12-month forecast. Week 4: Create a data room folder with 8–10 key documents.",
    },
  },
];

export const SCORE_LABELS = [
  { value: 0, short: "None",    full: "Not in place" },
  { value: 1, short: "Messy",   full: "Exists but messy / manual" },
  { value: 2, short: "Basic",   full: "Basic but inconsistent" },
  { value: 3, short: "Working", full: "Working consistently" },
  { value: 4, short: "Measured",full: "Measured & partly automated" },
  { value: 5, short: "Scaled",  full: "Optimized & scalable" },
] as const;

export const PROBLEM_ITEMS = [
  "Leads are not tracked properly",
  "Follow-ups are forgotten or delayed",
  "Proposals take too long to create",
  "Customer notes are scattered",
  "Sales pipeline is unclear",
  "Reporting is manual and time-consuming",
  "AI tools are used randomly, not systematically",
];
